#!/usr/bin/env bash
# One-command deploy for PSP Portal (GivTrade).
#
#   ./deploy.sh <domain> [acme-email]              # full stack + Caddy (auto HTTPS, owns 80/443)
#   ./deploy.sh <domain> --behind-proxy [--port=N] # app only on 127.0.0.1:N, use your own proxy
#
# Examples:
#   ./deploy.sh portal.giv.trade ops@giv.trade
#   ./deploy.sh portal.giv.trade --behind-proxy --port=8090
#
# Secrets are generated on first run and preserved on re-deploys.
set -euo pipefail
cd "$(dirname "$0")"

MODE="caddy"
WEB_PORT="8080"
ARGS=()
for a in "$@"; do
  case "$a" in
    --behind-proxy|--proxied) MODE="proxied" ;;
    --port=*) WEB_PORT="${a#*=}" ;;
    *) ARGS+=("$a") ;;
  esac
done

DOMAIN="${ARGS[0]:-}"
ACME_EMAIL="${ARGS[1]:-}"
if [ -z "$DOMAIN" ]; then
  echo "Usage:"
  echo "  ./deploy.sh <domain> [acme-email]              # with built-in Caddy (needs 80/443 free)"
  echo "  ./deploy.sh <domain> --behind-proxy [--port=N] # behind your existing reverse proxy"
  exit 1
fi
[ -z "$ACME_EMAIL" ] && ACME_EMAIL="admin@${DOMAIN}"

command -v docker >/dev/null 2>&1 || { echo "ERROR: Docker is not installed."; exit 1; }
docker compose version >/dev/null 2>&1 || { echo "ERROR: Docker Compose v2 is required."; exit 1; }

ENV_FILE=".env"
gen() {
  if command -v openssl >/dev/null 2>&1; then openssl rand -hex "$1"
  else head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n'; fi
}
get_var() {
  [ -f "$ENV_FILE" ] || return 0
  grep -E "^$1=" "$ENV_FILE" | head -1 | cut -d= -f2- | sed 's/^"//;s/"$//'
}

AUTH_SECRET="$(get_var AUTH_SECRET)";             [ -z "$AUTH_SECRET" ] && AUTH_SECRET="$(gen 32)"
POSTGRES_PASSWORD="$(get_var POSTGRES_PASSWORD)"; [ -z "$POSTGRES_PASSWORD" ] && POSTGRES_PASSWORD="$(gen 16)"
ADMIN_EMAIL="$(get_var ADMIN_EMAIL)";             [ -z "$ADMIN_EMAIL" ] && ADMIN_EMAIL="admin@${DOMAIN}"
ADMIN_PASSWORD="$(get_var ADMIN_PASSWORD)";       NEW_ADMIN=0
if [ -z "$ADMIN_PASSWORD" ]; then ADMIN_PASSWORD="$(gen 9)"; NEW_ADMIN=1; fi

cat > "$ENV_FILE" <<EOF
# Generated by deploy.sh — DO NOT COMMIT
DOMAIN=$DOMAIN
ACME_EMAIL=$ACME_EMAIL
APP_BASE_URL=https://$DOMAIN
AUTH_SECRET=$AUTH_SECRET
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
DATABASE_URL=postgresql://psp:$POSTGRES_PASSWORD@db:5432/psp_portal?schema=public
ADMIN_EMAIL=$ADMIN_EMAIL
ADMIN_PASSWORD=$ADMIN_PASSWORD
RUN_SEED=true
WEB_PORT=$WEB_PORT
EOF

if [ "$MODE" = "proxied" ]; then
  COMPOSE="docker-compose.proxied.yml"
  echo "==> [behind-proxy] Building db + web (app on 127.0.0.1:$WEB_PORT) ..."
else
  COMPOSE="docker-compose.prod.yml"
  echo "==> Building db + web + caddy for $DOMAIN ..."
fi

docker compose -f "$COMPOSE" up -d --build

echo
echo "============================================================"
echo " App:          https://$DOMAIN"
echo " Admin login:  https://$DOMAIN/login"
echo " Admin email:  $ADMIN_EMAIL"
if [ "$NEW_ADMIN" = "1" ]; then
  echo " Admin pass:   $ADMIN_PASSWORD   (change in Settings -> Account)"
else
  echo " Admin pass:   (unchanged from previous deploy)"
fi
echo "============================================================"

if [ "$MODE" = "proxied" ]; then
  cat <<EOF

The app listens on http://127.0.0.1:$WEB_PORT . Add ONE of these to your existing proxy:

  # --- nginx (then run: certbot --nginx -d $DOMAIN) ---
  server {
      server_name $DOMAIN;
      location / {
          proxy_pass http://127.0.0.1:$WEB_PORT;
          proxy_set_header Host \$host;
          proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto \$scheme;
      }
  }

  # --- Caddy (auto HTTPS) ---
  $DOMAIN {
      reverse_proxy 127.0.0.1:$WEB_PORT
  }
EOF
else
  cat <<EOF

Next:
  1) DNS A record: $DOMAIN -> this server's public IP
  2) Open ports 80 and 443 (Caddy needs them; make sure nothing else uses them)
  3) Caddy auto-issues the TLS cert on first request
EOF
fi

cat <<EOF

Also:
  - In MT5 Administrator, whitelist THIS server's public IP for the WebAPI manager.
  - Admin -> Settings: set Rival key, MT5 WebAPI host/login/password, min deposit, webhook.

Logs:   docker compose -f $COMPOSE logs -f
Stop:   docker compose -f $COMPOSE down
EOF
